project:
  type: website

website:
  title: "DARE 2024"
  search: False
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: index.qmd#participate
        text: Participate
      - href: index.qmd#program
        text: Program
      - href: index.qmd#speakers
        text: Speakers
      - href: index.qmd#organizers
        text: Organizers

format:
  html:
    theme: [cosmo,custom.scss]
    fontsize: "1.5em"
    page-layout: full
    css: styles.css
    toc: true

execute:
  freeze: auto


